# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.synced_folder "../", "/m2crypto"

  config.vm.provider "vmware_fusion" do |v|
    v.vmx["memsize"] = "4096"
    v.vmx["numvcpus"] = "2"
  end

  # OS X licensing doesn't allow distribution of VMs, you'll need to build your
  # own base VM, see:
  # https://github.com/google/grr-doc/blob/master/osxclient.adoc
  config.vm.define "OS_X_10.8.5" do |box|
    box.vm.box = "OS_X_10.8.5"
  end

end
